name: "Integration tests"
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install conntrack (mandatory for later k8s versions)
      run: sudo apt-get install -y conntrack
    - name: Setup Minikube
      id: minikube
      uses: ./
    - name: Launch Minikube
      run: eval ${{ steps.minikube.outputs.launcher }}
    - name: Install Nginx pod
      run: kubectl apply -f https://k8s.io/examples/application/deployment.yaml
    - name: Wait for pods
      uses: CodingNagger/minikube-wait-action@master
      with:
        namespace: default
        all-namespaces: false
    - name: Check pods
      run: |
        kubectl get pods

  update-version:
    if: github.ref == 'refs/heads/master'
    needs: integration-tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Authenticate Git User
      uses: fregante/setup-git-user@v1
    - name: Create version
      run: npm version patch

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.MINIKUB_SETUP_ACTION_TOKEN }}
  
